- name: Set virtual machine powerstate (vcenter)
  when:
  community.vmware.vmware_guest_powerstate:
    hostname: "{{ vcenter_hostname | mandatory }}"
    username: "{{ vcenter_username | mandatory }}"
    password: "{{ vcenter_password | mandatory }}"
    name: "{{ vm_name | mandatory }}"
    validate_certs: "{{ vcenter_validate_certs | default(False) }}"
    folder: "{{ vm_vcenter_path | default( '/' + vcenter_datacenter + '/vm/' + (vm_folder | default(''))) }}"
    state: "{{ vm_state | default('present') }}"
  register: powerstate_vm

